In [2]:
import pandas as pd

А теперь используем эти методы на знаменитом титаническом датасэте! Загрузите датасэт, посмотрите на датафрэйм и ответьте на вопросы

Комментарий: в ответе необходимо указать количество колонок.

Число колонок в представленном датафрэйме -- ?,
а число строк -- ?
Тип float имеют -- ? колонки,
int -- ?,
и object --?

In [4]:
titanic_df = pd.read_csv('https://stepik.org/media/attachments/course/4852/titanic.csv')

In [5]:
titanic_df.dtypes.value_counts()

int64      5
object     5
float64    2
dtype: int64